version: "2"

services:
  client:
    build: ./client
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3000:3000
    env_file: ./client/.env
    volumes:
      - ./client/src:/app/src

  backend:
    build: ./backend
    ports:
      - 9065:9065
    env_file: ./backend/.env
    volumes:
      - ./backend/src:/app/src
